---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sample
  labels:
    app: guestbook
    tier: frontend
spec:
  type: NodePort
  selector:
    app: guestbook
    tier: frontend
  ports:
  - port: 80
    targetPort: 80