apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  labels:
    component: logstash
  namespace: logging  
data:
  
  access-log.conf: |
    input {
      beats {
        port => "5044"
      }
    }    output {
      elasticsearch {
        hosts => [ "elasticsearch:9200" ]
        index => "logstash-001-%{+YYYY.MM.dd}"
      }
    }