apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-logstash
  name: logstash
  namespace: logging
spec:
  ports:
  - name: logstash
    port: 5044
    protocol: TCP
    targetPort: 5044
  selector:
    app: logstash


